config/routes.rb
Rails.application.routes.draw do

  root 'app_pages#home'

  devise_for :users, skip: [:sessions]

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get 'home', to: 'app_pages#home'
  get 'calendar', to: 'app_pages#calendar'
  get 'day', to: 'app_pages#day'

  resources :foods, only: [:create, :destroy]
  resources :exercises, only: [:create, :destroy]

  patch 'goals', to: 'users#change_goals'

  

end

app/models/daily_activity.rb
class DailyActivity < ActiveRecord::Base
  belongs_to :user
  has_many :exercises, dependent: :destroy
  has_many :foods, dependent: :destroy

  def exercise_calories
    self.exercises.sum(:calories)
  end

  def food_calories
    self.foods.sum(:calories)
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :daily_activity
  validates :name, presence: true
  validates :calories, presence: true
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :daily_activity
  validates :name, presence: true
  validates :calories, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_initialize :init

  has_many :daily_activities, dependent: :destroy
  has_many :foods, through: :daily_activities
  has_many :exercises, through: :daily_activities


  
  def init
    self.food_goal = 2000
    self.exercise_goal = 600 
  end
end

app/controllers/app_pages_controller.rb
class AppPagesController < ApplicationController
  before_action :authenticate_user!, except: :home

  def home
    unless current_user
      flash[:notice] = notice if notice
      redirect_to new_user_session_path
    else
      todays_activity = current_user.daily_activities.find_by(date: Date.today)
      @food_goal = current_user.food_goal
      @exercise_goal = current_user.exercise_goal

      if todays_activity
        @food_current = todays_activity.food_calories 
        @current_food_progress = @food_goal - @food_current
        @exercise_current = todays_activity.exercise_calories
      else
        @food_current = @exercise_current = 0
        @current_food_progress = @food_goal
      end
    end
  end

  def calendar
    @food = Food.new
    @exercise = Exercise.new
  end

  def day
    @days_activity = current_user.daily_activities.find_by(date: params[:date])
    unless @days_activity
      @days_activity = current_user.daily_activities.create(date: params[:date])
    end
    @foods = @days_activity.foods
    @exercises = @days_activity.exercises

    respond_to do |format|
      format.js { render 'day', layout: false }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    activities_list = current_user.daily_activities.find_by(date: params[:date])
    unless activities_list
      activities_list = current_user.daily_activities.create(date: params[:date])
    end

    exercise = activities_list.exercises.new(exercise_params)
    if exercise.save
      flash[:notice] = "Activity was added to the list"
    else
      flash[:alert] = "Something went wrong. Exercise isn't added"
    end
    redirect_to calendar_path(start_date: params[:date])
  end

  def destroy
    exercise = current_user.exercises.find(params[:id])
    exercise.destroy

    render nothing: true
  end


  private
    def exercise_params
      params.require(:exercise).permit(:name, :calories)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def create
    activities_list = current_user.daily_activities.find_by(date: params[:date])
    unless activities_list
      activities_list = current_user.daily_activities.create(date: params[:date])
    end

    food = activities_list.foods.new(food_params)
    if food.save
      flash[:notice] = "Food was added to the list"
    else
      flash[:alert] = "Something went wrong. Food isn't added"
    end
    redirect_to calendar_path(start_date: params[:date])
  end

  def destroy
    food = current_user.foods.find(params[:id])
    food.destroy

    render nothing: true
  end

  private
    def food_params
      params.require(:food).permit(:name, :calories)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def change_goals
    current_user.update_attributes(food_goal: params[:food_goal], exercise_goal: params[:exercise_goal])

    flash[:notice] = "Calorie goals were changed"
    redirect_to calendar_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
     flash.now[:alert] = resource.errors.full_messages.first
  end
end

app/views/app_pages/_day.html.erb
<!-- goes inside #day_tab -->
<div class="day-container">
  <div id="day_date_hidden"><%= @days_activity.date.strftime("%Y-%m-%d") %></div>
  <div class="day-info">
    <span class="calendar-link">< Back to the calendar</span>
    
    <div class="day-date"><%= @days_activity.date.strftime("%e %B %y") %></div>
  </div>

  <div class="day-tabs">
    <div id="open_food_table" class="active-day-tab">Food tab</div>
    <div id="open_exercise_table">Exercise tab</div>
  </div>
  
  <div class="day-table-container day-table-active" id="food_table">
    <table>
      <thead>
        <tr>
          <td class="head-count">#</td>
          <td class="head-name">Name</td>
          <td class="head-calories">Calories</td>
          <td class="head-remove">Remove</td>
        </tr>
      </thead>

      <tbody>
        <% @foods.each_with_index do |food, i| %>
          <tr>
            <td class="body-count"><%= i+1 %></td>
            <td class="body-name"><%= food.name %></td>
            <td class="body-calories"><%= food.calories %></td>
            <td class="body-remove"><%= link_to '-X-', food_path(food), remote: true, method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="day-table-container" id="exercise_table">
    <table>
      <thead>
        <tr>
          <td class="head-count">#</td>
          <td class="head-name">Name</td>
          <td class="head-calories">Calories</td>
          <td class="head-remove">Remove</td>
        </tr>
      </thead>

      <tbody>
        <% @exercises.each_with_index do |exercise, i| %>
          <tr>
            <td class="body-count"><%= i+1 %></td>
            <td class="body-name"><%= exercise.name %></td>
            <td class="body-calories"><%= exercise.calories %></td>
            <td class="body-remove"><%= link_to '-X-', exercise_path(exercise), remote: true, method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/app_pages/calendar.html.erb
<div id="calendar_tab" class="tab-container tab-active">
  <div id="calendar_default">
    <div class="calendar-container">
      <%= week_calendar number_of_weeks: 2 do |date| %>
        <%= link_to day_path(date: date), remote: true, id: "#{date}", class: "form-day-link" do %>
          <span class="table-cell-date"><%= date.strftime("%d %b") %></span>
          <div class="table-cell-counters">
            <% day = current_user.daily_activities.find_by(date: date) %>
            <% if day %>
              <p class="cell-foods">Eaten<br /><span class="cell-foods-count"><%= day.food_calories %></span></p>
              <p class="cell-exercises">Burned<br /><span class="cell-exercises-count"><%= day.exercise_calories %></span></p>
            <% else %>
              <p class="cell-foods">Eaten<br />0</p>
              <p class="cell-exercises">Burned<br />0</p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="day_tab" class="tab-container">
  </div>
</div>


<div id="food_tab" class="tab-container">
  <h3>Add food</h3>
  <%= form_for @food, url: {controller: "foods", action: "create"}, html: {class: "add-form"} do |f| %>
    <%= f.text_field :name, placeholder: "Food name", required: true %>
    <%= f.number_field :calories, placeholder: "Amount of calories", required: true %><br />
    <span class="form-date">Date:</span>
    <%= date_field_tag(:date, Date.today, required: true) %><br />
    <%= f.submit "Add food" %>
  <% end %>
</div>


<div id="exercise_tab" class="tab-container">
  <h3>Add activity</h3>
  <%= form_for @exercise, url: {controller: "exercises", action: "create"}, html: {class: "add-form"} do |f| %>
    <%= f.text_field :name, placeholder: "Activity name", required: true %>
    <%= f.number_field :calories, placeholder: "Amount of calories", required: true %><br />
    <span class="form-date">Date:</span>
    <%= date_field_tag(:date, Date.today, required: true) %><br />
    <%= f.submit "Add activity" %>
  <% end %>
</div>


<div id="goals_tab" class="tab-container">
  <h3>Change your calorie goals</h3>
  <%= form_tag goals_path, method: :patch, class: 'goals-form' do %>
    <div class="goals-group">
      <%= label_tag 'food_goal', "Food:", class: 'goal-label' %>
      <%= number_field_tag 'food_goal', current_user.food_goal , class: 'calorie-goal-input', required: true %>
    </div>
    <div class="goals-group">
      <%= label_tag 'exercise_goal', "Activity:", class: 'goal-label' %>
      <%= number_field_tag 'exercise_goal', current_user.exercise_goal, class: 'calorie-goal-input', required: true %>
    </div>
    <%= submit_tag "Change goals", class: "calorie-goal-submit" %>
  <% end %>
</div>








<aside class="activity-options">
  <div class="activity-item activity-active" id="open_calendar_tab">Show Calendar</div>
  <div class="activity-item" id="open_food_tab">Add Food</div>
  <div class="activity-item" id="open_exercise_tab">Add Activity</div>
  <div class="activity-item" id="open_goals_tab">Change Goals</div>
</aside>

app/views/app_pages/calendar.js.erb
$("#calendar_default").html("<%= escape_javascript(render 'app_pages/calendar') %>");

app/views/app_pages/checklist.html.erb
<div class="calendar-container">
  <%= week_calendar number_of_weeks: 2 do |date| %>
    <span class="table-cell-date"><%= date.strftime("%d %b") %></span>
    <div class="table-cell-counters">
      <% day = current_user.daily_activities.find_by(date: date) %>
      <% if day %>
        <p class="cell-foods">Eaten<br /><%= day.food_calories %></p>
        <p class="cell-exercises">Burned<br /><%= day.exercise_calories %></p>
      <% else %>
        <p class="cell-foods">Eaten<br />0</p>
        <p class="cell-exercises">Burned<br />0</p>
      <% end %>
    </div>
  <% end %>
</div>

<aside class="activity-options">
  <div class="activity-item" id="activities_show_calendar">Show Calendar</div>
  <div class="activity-item" id="activities_add_food">Add Food</div>
  <div class="activity-item" id="activities_add_exercise">Add Activity</div>
  <div class="activity-item" id="activities_change_goals">Change Goals</div>
</aside>

app/views/app_pages/day.js.erb
$("#day_tab").html("<%= escape_javascript(render 'app_pages/day') %>");
$("#calendar_default").hide();
$("#day_tab").show();

app/views/app_pages/home.html.erb
<div class="calories-main">
  <span id="calories-food-hidden"><%= @food_goal %></span>
  <span id="calories-exercise-hidden"><%= @exercise_goal %></span>

  <div class="calories-eaten">
    <span class="calories-data-title">EATEN</span>
    <div class="calories-data-info">
      <span id="calories-eaten"><%= @food_current %></span>
      <p>KCAL</p>
    </div>
    <div class="calories-canvas-container">
      <canvas id="calories_eaten_canvas" width="44" height=44>
        Sorry, your browser does not support canvas.
      </canvas>
    </div>
  </div>


  <div class="calories-left">
    <div class="calories-left-counter">
      <span id="calories-left-value"><%= @current_food_progress > 0 ? @current_food_progress : 0 %></span>
      <p>LEFT</p>
    </div>
    <canvas id="calories_left_canvas" width="220" height=220>
      Sorry, your browser does not support canvas.
    </canvas>
  </div>


  <div class="calories-burned">
    <span class="calories-data-title">BURNED</span>
    <div class="calories-data-info">
      <span id="calories-burned"><%= @exercise_current %></span>
      <p>KCAL</p>
    </div>
    <div class="calories-canvas-container">
      <canvas id="calories_burned_canvas" width="44" height=44>
        Sorry, your browser does not support canvas.
      </canvas>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Personalizer</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice && !notice.blank? %>
  <div id='flash_message' class='flash-notice'><%= notice %>
    <div class="close-notice" id='close_flash_message'>X</div>
  </div>
<% end %>

<% if alert && !alert.blank? %>
  <div id='flash_message' class='flash-alert'><%= alert %>
    <div class="close-notice" id='close_flash_message'>X</div>
  </div>
<% end %>


<div class="bg1"></div>
<svg class="bg2" viewBox="0 0 987.18375 987.18375">
  <g id="layer1" transform="translate(-440.69 -187.34)">
    <rect id="rect3352" fill-rule="evenodd" transform="rotate(135)" height="696.14" width="696.14" y="-1490.2" x="-527.22" fill="#9354e0"/>
  </g>
</svg>


<div class="app-container">
  <div class="side-panel" <%= 'id=rolled' if current_page?(root_path) %>>
    <div class="side-panel-fill"></div>
    <ul class="panel-options">
      <% unless current_user %> 
        <li class="panel-option">
          <svg class="icon1" viewBox="0 0 35 35">
            <g>
              <rect width="13" height="13" rx="1" ry="1" x="1"  y="1"/>
              <rect width="13" height="13" rx="1" ry="1" x="20" y="1"/>
              <rect width="13" height="13" rx="1" ry="1" x="1"  y="20" />
              <rect width="13" height="13" rx="1" ry="1" x="20" y="20" />
            </g>
          </svg>
        </li>
      <% end %>
      
      <% if current_user %>

      <li class="panel-option">
        <!-- link needs to request a full url for rolling the panel -->
        <%= link_to root_url, { class: "panel-option-link", id: "panel_link"} do %>
          <svg class="icon1" viewBox="0 0 35 35">
            <g>
              <rect width="13" height="13" rx="1" ry="1" x="1"  y="1"/>
              <rect width="13" height="13" rx="1" ry="1" x="20" y="1"/>
              <rect width="13" height="13" rx="1" ry="1" x="1"  y="20" />
              <rect width="13" height="13" rx="1" ry="1" x="20" y="20" />
            </g>
          </svg>
        <% end %>
      </li>

      <li class="panel-option">
        <%= link_to calendar_path, {class: 'panel-option-link'} do %>
          <svg class="icon2" viewBox="0 0 60 60">
            <g>
              <path d="M57,4h-7V1c0-0.553-0.447-1-1-1h-7c-0.553,0-1,0.447-1,1v3H19V1c0-0.553-0.447-1-1-1h-7c-0.553,0-1,0.447-1,1v3H3
                C2.447,4,2,4.447,2,5v11v43c0,0.553,0.447,1,1,1h54c0.553,0,1-0.447,1-1V16V5C58,4.447,57.553,4,57,4z M43,2h5v3v3h-5V5V2z M12,2h5
                v3v3h-5V5V2z M4,6h6v3c0,0.553,0.447,1,1,1h7c0.553,0,1-0.447,1-1V6h22v3c0,0.553,0.447,1,1,1h7c0.553,0,1-0.447,1-1V6h6v9H4V6z
                 M4,58V17h52v41H4z"/>
              <path d="M38,23h-7h-2h-7h-2h-9v9v2v7v2v9h9h2h7h2h7h2h9v-9v-2v-7v-2v-9h-9H38z M31,25h7v7h-7V25z M38,41h-7v-7h7V41z M22,34h7v7h-7
                V34z M22,25h7v7h-7V25z M13,25h7v7h-7V25z M13,34h7v7h-7V34z M20,50h-7v-7h7V50z M29,50h-7v-7h7V50z M38,50h-7v-7h7V50z M47,50h-7
                v-7h7V50z M47,41h-7v-7h7V41z M47,25v7h-7v-7H47z"/>
            </g>
          </svg>

        <% end %>
      </li>
      <li class="panel-option">
        <%= link_to edit_user_registration_path, {class: 'panel-option-link'} do %>
          <svg class="icon3" viewBox="0 0 482.9 482.9">
            <g>
              <g>
                <path d="M239.7,260.2c0.5,0,1,0,1.6,0c0.2,0,0.4,0,0.6,0c0.3,0,0.7,0,1,0c29.3-0.5,53-10.8,70.5-30.5
                  c38.5-43.4,32.1-117.8,31.4-124.9c-2.5-53.3-27.7-78.8-48.5-90.7C280.8,5.2,262.7,0.4,242.5,0h-0.7c-0.1,0-0.3,0-0.4,0h-0.6
                  c-11.1,0-32.9,1.8-53.8,13.7c-21,11.9-46.6,37.4-49.1,91.1c-0.7,7.1-7.1,81.5,31.4,124.9C186.7,249.4,210.4,259.7,239.7,260.2z
                   M164.6,107.3c0-0.3,0.1-0.6,0.1-0.8c3.3-71.7,54.2-79.4,76-79.4h0.4c0.2,0,0.5,0,0.8,0c27,0.6,72.9,11.6,76,79.4
                  c0,0.3,0,0.6,0.1,0.8c0.1,0.7,7.1,68.7-24.7,104.5c-12.6,14.2-29.4,21.2-51.5,21.4c-0.2,0-0.3,0-0.5,0l0,0c-0.2,0-0.3,0-0.5,0
                  c-22-0.2-38.9-7.2-51.4-21.4C157.7,176.2,164.5,107.9,164.6,107.3z"/>
                <path d="M446.8,383.6c0-0.1,0-0.2,0-0.3c0-0.8-0.1-1.6-0.1-2.5c-0.6-19.8-1.9-66.1-45.3-80.9c-0.3-0.1-0.7-0.2-1-0.3
                  c-45.1-11.5-82.6-37.5-83-37.8c-6.1-4.3-14.5-2.8-18.8,3.3c-4.3,6.1-2.8,14.5,3.3,18.8c1.7,1.2,41.5,28.9,91.3,41.7
                  c23.3,8.3,25.9,33.2,26.6,56c0,0.9,0,1.7,0.1,2.5c0.1,9-0.5,22.9-2.1,30.9c-16.2,9.2-79.7,41-176.3,41
                  c-96.2,0-160.1-31.9-176.4-41.1c-1.6-8-2.3-21.9-2.1-30.9c0-0.8,0.1-1.6,0.1-2.5c0.7-22.8,3.3-47.7,26.6-56
                  c49.8-12.8,89.6-40.6,91.3-41.7c6.1-4.3,7.6-12.7,3.3-18.8c-4.3-6.1-12.7-7.6-18.8-3.3c-0.4,0.3-37.7,26.3-83,37.8
                  c-0.4,0.1-0.7,0.2-1,0.3c-43.4,14.9-44.7,61.2-45.3,80.9c0,0.9,0,1.7-0.1,2.5c0,0.1,0,0.2,0,0.3c-0.1,5.2-0.2,31.9,5.1,45.3
                  c1,2.6,2.8,4.8,5.2,6.3c3,2,74.9,47.8,195.2,47.8s192.2-45.9,195.2-47.8c2.3-1.5,4.2-3.7,5.2-6.3
                  C447,415.5,446.9,388.8,446.8,383.6z"/>
              </g>                                                   
            </g>
          </svg>
        <% end %>
      </li>
      <li class="panel-option">
        <%= link_to destroy_user_session_path, {method: :delete, class: 'panel-option-link'} do %>
          <svg class="icon4" viewBox="0 0 330 330">
            <g id="XMLID_2_">
              <path id="XMLID_4_" d="M51.213,180h173.785c8.284,0,15-6.716,15-15s-6.716-15-15-15H51.213l19.394-19.393
                c5.858-5.857,5.858-15.355,0-21.213c-5.856-5.858-15.354-5.858-21.213,0L4.397,154.391c-0.348,0.347-0.676,0.71-0.988,1.09
                c-0.076,0.093-0.141,0.193-0.215,0.288c-0.229,0.291-0.454,0.583-0.66,0.891c-0.06,0.09-0.109,0.185-0.168,0.276
                c-0.206,0.322-0.408,0.647-0.59,0.986c-0.035,0.067-0.064,0.138-0.099,0.205c-0.189,0.367-0.371,0.739-0.53,1.123
                c-0.02,0.047-0.034,0.097-0.053,0.145c-0.163,0.404-0.314,0.813-0.442,1.234c-0.017,0.053-0.026,0.108-0.041,0.162
                c-0.121,0.413-0.232,0.83-0.317,1.257c-0.025,0.127-0.036,0.258-0.059,0.386c-0.062,0.354-0.124,0.708-0.159,1.069
                C0.025,163.998,0,164.498,0,165s0.025,1.002,0.076,1.498c0.035,0.366,0.099,0.723,0.16,1.08c0.022,0.124,0.033,0.251,0.058,0.374
                c0.086,0.431,0.196,0.852,0.318,1.269c0.015,0.049,0.024,0.101,0.039,0.15c0.129,0.423,0.28,0.836,0.445,1.244
                c0.018,0.044,0.031,0.091,0.05,0.135c0.16,0.387,0.343,0.761,0.534,1.13c0.033,0.065,0.061,0.133,0.095,0.198
                c0.184,0.341,0.387,0.669,0.596,0.994c0.056,0.088,0.104,0.181,0.162,0.267c0.207,0.309,0.434,0.603,0.662,0.895
                c0.073,0.094,0.138,0.193,0.213,0.285c0.313,0.379,0.641,0.743,0.988,1.09l44.997,44.997C52.322,223.536,56.161,225,60,225
                s7.678-1.464,10.606-4.394c5.858-5.858,5.858-15.355,0-21.213L51.213,180z"/>
              <path id="XMLID_5_" d="M207.299,42.299c-40.944,0-79.038,20.312-101.903,54.333c-4.62,6.875-2.792,16.195,4.083,20.816
                c6.876,4.62,16.195,2.794,20.817-4.083c17.281-25.715,46.067-41.067,77.003-41.067C258.414,72.299,300,113.884,300,165
                s-41.586,92.701-92.701,92.701c-30.845,0-59.584-15.283-76.878-40.881c-4.639-6.865-13.961-8.669-20.827-4.032
                c-6.864,4.638-8.67,13.962-4.032,20.826c22.881,33.868,60.913,54.087,101.737,54.087C274.956,287.701,330,232.658,330,165
                S274.956,42.299,207.299,42.299z"/>
            </g>
          </svg>
        <% end %>
      </li>

      <% end %>
      
    </ul>
  </div>    

  <div class="main-panel">


    <%= yield %>


  </div>
</div>  

</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '< Previous'), (calendar.url_for_previous_view[0..-11] + (calendar.url_for_previous_view[-10..-1].to_date - 1.week).to_s ) %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next >'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>